version: "3.7"
volumes:
    cmdbuild-db:
    cmdbuild-tomcat:

services:
    cmdbuild_db:
        image: cavamagie/postgresql-with-bck
        container_name: cmdbuild_db
        volumes:
            - cmdbuild-db:/var/lib/postgresql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_DB=cmdbuild_3
        restart: on-failure
        deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 1000M
            reservations:
              cpus: '0.25'
              memory: 300m        

    cmdbuild_run:
        image: cavamagie/cmdbuild-3.1.1
        container_name: cmdbuild_run
        links:
           - cmdbuild_db
        depends_on:
           - cmdbuild_db
        ports:
            - 8080:8080
        restart: on-failure    
        volumes:
            - cmdbuild-tomcat:/usr/local/tomcat
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASS=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=cmdbuild_db
            - POSTGRES_DB=cmdbuild_31
            - CMDBUILD_DUMP=demo
            - JAVA_OPTS=-Xmx4000m -Xms2000m
        deploy:
          resources:
            limits:
              memory: 4000M
            reservations:
              memory: 2000m              
